OBJS   := $(wildcard *.cpp)
OBJS   := $(OBJS:.cpp=.o)
OUT    := $(SUBDIR).o
CFLAGS += -I$(INCLUDE_DIR)/$(SUBDIR)



all: $(OUT)


$(OUT): $(OBJS)
	$(LD) -r $(OBJS) -o ../$(OUT) 


.cpp.o:
	$(CC) $(CFLAGS) -o $@ -c $<


clean:
	$(CLEAN) $(OBJS)

