SUBDIRS := ${shell find * -type d -print}
OBJS    += $(SUBDIRS:=.o)



all: $(PROJECT_NAME)


$(PROJECT_NAME): subdirs $(OBJS)
	$(CC) $(OBJS) -o $(PROJECT_NAME) $(LDFLAGS)
	$(STRIP) $(PROJECT_NAME)


subdirs: $(SUBDIRS)
	for dir in $(SUBDIRS); do \
		export SUBDIR=$$dir; \
		$(MAKESUB); \
	done


clean: clean-subdirs
	$(CLEAN) $(PROJECT_NAME) $(OBJS)


clean-subdirs:
	for dir in $(SUBDIRS); do \
		$(MAKESUB) clean; \
	done
