OBJS   := $(wildcard *.cpp)
OBJS   := $(OBJS:.cpp=.o)
OUT    := $(SUBDIR).o



all: $(OUT)


$(OUT): $(OBJS)
	$(LD) -r $(OBJS) -o ../$(OUT)


.cpp.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	$(CLEAN) $(OBJS)
