SUBDIRS := ${shell find * -type d -print}
OBJS    += $(SUBDIRS:=.o)



all: $(PROJECT)


$(PROJECT): subdirs
	$(CC) $(OBJS) -o ../$(PROJECT) $(LDFLAGS)
	$(CLEAN) $(OBJS)


subdirs: $(SUBDIRS)
	for dir in $(SUBDIRS); do \
		export SUBDIR=$$dir;  \
		$(MAKESUB);           \
	done

clean: clean-subdirs
	for dir in $(SUBDIRS); do                           \
		$(MAKE) -C $$dir -f $(PWD)/Makefile.sub clean; \
	done

clean-subdirs:
	$(CLEAN) $(OBJS)
