SUBDIRS := ${shell find * -type d -print}
OBJS    += $(SUBDIRS:=.o)



all: $(PROJECT)


$(PROJECT): subdirs $(OBJS)
	$(CC) $(OBJS) -o ../$(PROJECT) $(LDFLAGS)
	$(CLEAN) $(OBJS)


subdirs: $(SUBDIRS)
	$(CLEAN) $(OBJS)
	for dir in $(SUBDIRS); do \
		export SUBDIR=$$dir;  \
		$(MAKESUB);           \
	done

clean:
	for dir in $(SUBDIRS); do                           \
		$(MAKE) -C $$dir -f $(PWD)/Makefile.sub clean; \
	done
	$(CLEAN) $(OBJS)
